version: "3.8"


services:
  web:
    image: gitea/gitea:1.12
    container_name: cicd_gitea
    restart: always
    volumes:
      - data:/data
    ports:
      - "3000:3000"
      - "22:22"
    depends_on:
      - db
    networks:
      cicd:
        aliases:
          - gitea

  db:
    image: mariadb:10.5
    container_name: cicd_gitea-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/dbroot_password
      - MYSQL_DATABASE=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD_FILE=/run/secrets/db_password
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306
    secrets:
      - db_password
      - dbroot_password
    networks:
      cicd:
        aliases:
          - gitea_db

  dbbackup:
    image: dockerRepository:5000/periodic-backup:28
    container_name: cicd_gitea-dbbackup
    restart: always
    depends_on:
      - db
    environment:
      - MYSQL_CONTAINER_NAME=db
      - MYSQL_DATABASE=gitea
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/dbroot_password
      - KEEP_DAILY=7
      - KEEP_WEEKLY=5
      - KEEP_MONTHLY=12
    secrets:
      - dbroot_password
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - dbDumps:/opt/mysql/backup
    command: crond -f -d 8
    networks:
      cicd:
        aliases:
          - gitea_dbBackup


networks:
  cicd:
    name: cicd

volumes:
  data:
    name: gitea_data
  db:
    name: gitea_db
  dbDumps:
    name: gitea_dbDumps

secrets:
  db_password:
    file: ./db_password.txt
  dbroot_password:
    file: ./dbroot_password.txt
