version: "3.8"

services:

  docker-registry:
    container_name: docker-registry
    restart: always
    image: registry:2
    ports:
      - ${DOCKER_REGISTRY_PORT}:5000
    volumes:
      - docker_registry:/var/lib/registry
    networks:
      cicd:
        aliases:
         - docker-registry

  docker:
    container_name: docker
    restart: always
    image: docker:dind
    privileged: yes
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - docker:/var/lib/docker
      - docker_certs:/certs/client
    command: --insecure-registry "docker-registry:5000"
    networks:
      cicd:
        aliases:
          - docker

  jenkins:
    container_name: jenkins
    restart: always
    image: jenkinsci/blueocean:latest
    ports:
      - ${BUILD_SERVER_PORT}:8080
    environment:      
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - docker_certs:/certs/client:ro
      - jenkins_home:/var/jenkins_home
    networks:
      cicd:
        aliases:
          - jenkins

  baget:
    container_name: baget
    restart: always
    image: loicsharma/baget
    depends_on:
      - baget-db
    ports:
      - ${NUGET_PORT}:80
    environment:      
      - Storage__Type=FileSystem
      - Storage__Path=/var/baget/packages
      - Database__Type=MySql
      - Database__ConnectionString=Server=baget-db;Port=3306;Database=${MYSQL_DATABASE};Uid=baget;Pwd=${MYSQL_PASSWORD}
      - Search__Type=Database
    volumes:
      - baget_data:/var/baget
    networks:
      cicd:
        aliases:
          - nuget-repo

  baget-db:
    image: mariadb:10.5
    restart: always
    container_name: baget-db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - ${NUGET_DB_PORT}:3306
    volumes:
      - baget_db:/var/lib/mysql
    networks:
      - cicd


volumes:
  docker:
    name: docker
  docker_certs:
    name: docker_certs
  docker_registry:
    name: docker_registry
  jenkins_home:
    name: jenkins_home
  baget_data:
    name: baget_data
  baget_db:
    name: baget_dbdata

networks:
  cicd:
    name: cicd
