version: "3.8"

services:

  docker-registry:
    container_name: docker-registry
    restart: always
    image: registry:2
    ports:
      - 5000:5000
    volumes:
      - docker_registry:/var/lib/registry
    networks:
      cicd:
        aliases:
         - dockerRegistry

  docker:
    container_name: docker
    restart: always
    image: docker:dind
    privileged: yes
    # Uncomment env file when you run "docker compose up" manually
    # env_file:
    #   - cicd.env
    volumes:
      - docker:/var/lib/docker
      - docker_certs:/certs/client
    command: --insecure-registry "dockerRegistry:5000"
    networks:
      cicd:
        aliases:
          - docker

  jenkins:
    container_name: jenkins
    restart: always
    image: jenkinsci/blueocean:latest
    # Uncomment env file when you run "docker compose up" manually
    # env_file:
    #   - cicd.env
    ports:
      - ${JENKINS_PORT}:8080
    volumes:
      - docker_certs:/certs/client:ro
      - jenkins_home:/var/jenkins_home
    networks:
      cicd:
        aliases:
          - jenkins

  baget:
    container_name: baget
    restart: always
    image: loicsharma/baget
    depends_on:
      - baget-db
    # Uncomment env file when you run "docker compose up" manually
    # env_file:
    #   - cicd.env
    ports:
      - ${BAGET_PORT}:80
    volumes:
      - baget_data:/var/baget
    networks:
      cicd:
        aliases:
          - nugetRepo

  baget_db:
    image: mariadb:10.5
    restart: always
    container_name: baget-db
    # Uncomment env file when you run "docker compose up" manually
    # env_file:
    #   - cicd.env
    ports:
      - ${NUGET_DB_PORT}:3306
    volumes:
      - baget_db:/var/lib/mysql
    networks:
      cicd:
        aliases:
          - baget_db


  baget_dbbackup:
    container_name: baget-dbbackup
    image: ${DOCKER_REGISTRY}/periodic-backup:28
    depends_on:
      - baget-db
    # Uncomment env file when you run "docker compose up" manually
    # env_file:
    #   - cicd.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - baget_dbdumps:/opt/mysql/backup
    networks:
      cicd:
        aliases:
          - baget_dbbackup
    command: crond -f -d 8
    restart: always


volumes:
  docker:
    name: docker
  docker_certs:
    name: docker_certs
  docker_registry:
    name: docker_registry
  jenkins_home:
    name: jenkins_home
  baget_data:
    name: baget_data
  baget_db:
    name: baget_dbdata
  baget_dbdumps:
    name: baget_dbdumps

networks:
  cicd:
    name: cicd
