version: "3.8"

services:

  docker-registry:
    container_name: cicd_docker-registry
    restart: always
    image: registry:2
    ports:
      - 5000:5000
    volumes:
      - docker_registry:/var/lib/registry
    networks:
      cicd:
        aliases:
         - dockerRegistry

  docker:
    container_name: cicd_docker
    restart: always
    image: docker:dind
    privileged: yes
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - docker:/var/lib/docker
      - docker_certs:/certs/client
    command: --insecure-registry "dockerRegistry:5000"
    networks:
      cicd:
        aliases:
          - docker

  jenkins:
    container_name: cicd_jenkins
    restart: always
    image: jenkinsci/blueocean:latest
    ports:
      - 8080:8080
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - docker_certs:/certs/client:ro
      - jenkins_home:/var/jenkins_home
    networks:
      cicd:
        aliases:
          - jenkins


volumes:
  docker:
    name: docker
  docker_certs:
    name: docker_certs
  docker_registry:
    name: docker_registry
  jenkins_home:
    name: jenkins_home

networks:
  cicd:
    name: cicd
