version: "2.2"
services:

  jenkins-docker-registry:
    container_name: jenkins-docker-registry
    restart: always
    ports:
      - 5000:5000
    image: registry:2
    volumes:
      - docker_registry:/var/lib/registry
    networks:
      jenkins:
        aliases:
         - dockerRegistry

  jenkins-docker:
    container_name: jenkins-docker
    privileged: yes
    environment:
      DOCKER_TLS_CERTDIR: "/certs"
    volumes:
      - docker:/var/lib/docker
      - docker_certs:/certs/client
    image: docker:dind
    command: --insecure-registry "dockerRegistry:5000"
    networks:
      jenkins:
        aliases:
          - docker

  jenkins:
    container_name: jenkins
    ports:
      - 8080:8080
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: "/certs/client"
      DOCKER_TLS_VERIFY: 1
    volumes:
      - docker_certs:/certs/client:ro
      - home:/var/jenkins_home
    image: jenkinsci/blueocean:latest
    networks:
      - jenkins

volumes:
  docker:
  docker_certs:
  home:
  docker_registry:

networks:
  jenkins: