version: "2.2"
services:
  jenkins-docker-registry:
    container_name: jenkins-docker-registry
    restart: always
    ports:
      - 5000:5000
    image: registry:2

  jenkins-docker:
    container_name: jenkins-docker
    restart: always
    privileged: yes
    environment:
      DOCKER_TLS_CERTDIR: "/certs"
    volumes:
      - docker:/var/lib/docker
      - docker_certs:/certs/client
    image: docker:dind
    networks:
      jenkins:
        aliases:
          - docker

  jenkins:
    container_name: jenkins
    restart: always
    ports:
      - 8081:8080
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: "/certs/client"
      DOCKER_TLS_VERIFY: 1
    volumes:
      - docker_certs:/certs/client:ro
      - home:/var/jenkins_home
    image: jenkinsci/blueocean
    networks:
      - jenkins

volumes:
  docker:
  docker_certs:
  home:

networks:
  jenkins: