version: "3.8"

services:

  restic:
    container_name: restic
    image: mazzolino/restic
    hostname: docker
    environment:
        BACKUP_CRON: "0 2 * * *"
        RESTIC_PASSWORD: XXXXXXXXXXX
        RESTIC_BACKUP_SOURCES: /source
        RESTIC_FORGET_ARGS: --keep-daily 7 --keep-weekly 4 --keep-monthly 12 --keep-yearly 1
    volumes:
      - restic_repo:/mnt/restic
      - portainer_data:/source/portainer_data:ro
      - grafana_data:/source/grafana_data:ro
      - ioBroker_dbdata:/source/ioBroker_dbdata:ro
      - jenkins_home:/source/jenkins_home:ro
      - trilium_trilium:/source/trilium_trilium:ro
      - baget_data:/source/baget_data:ro
      - baget_dbdata:/source/baget_dbdata:ro
      - gitea_data:/source/gitea_data:ro
      - gitea_db:/source/gitea_db:ro

volumes:
  restic_repo:
    name: restic_repo
  portainer_data:
    name: portainer_data
  grafana_data:
    name: grafana_data
  ioBroker_dbdata:
    name: ioBroker_dbdata
  jenkins_home:
    name: jenkins_home
  trilium_trilium:
    name: trilium_trilium
  baget_data:
    name: baget_data
  baget_dbdata:
    name: baget_dbdata
  gitea_data:
    name: gitea_data
  gitea_db:
    name: gitea_db
