version: '2'

services:
  portainer:
    container_name: portainer-1.24.0_2
    image: portainer/portainer:1.24.0
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data

volumes:
  data: