version: '3.8'

services:
  portainer:
    container_name: portainer-ce
    image: portainer/portainer-ce:2.11.1
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - ${PORTAINER_PORT}:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data

volumes:
  data: