version: "3.8"

services:

  ioBroker-db:
    container_name: ioBroker-db
    image: mariadb:10.5
    restart: always
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/dbroot_password
      - MYSQL_DATABASE=ioBroker
      - MYSQL_USER=ioBroker
      - MYSQL_PASSWORD_FILE=/run/secrets/db_password
    secrets:
      - db_password
      - dbroot_password


  ioBroker-dbbackup:
    container_name: ioBroker-dbbackup
    image: dockerRegistry:5000/periodic-backup:21
    depends_on:
      - ioBroker-db
    environment:
      - MYSQL_CONTAINER_NAME=ioBroker-db
      - MYSQL_DATABASE=ioBroker
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/dbroot_password
      - KEEP_DAILY=7
      - KEEP_WEEKLY=5
      - KEEP_MONTHLY=12
    secrets:
      - dbroot_password
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - dbdumps:/opt/mysql/backup
    command: crond -f -d 8
    restart: always

volumes:
  dbdata:
    name: ioBroker_dbdata
  dbdumps:
    name: ioBroker_dbdumps

secrets:
  db_password:
    file: ./db_password.txt
  dbroot_password:
    file: ./dbroot_password.txt